### ISSUE TITLE
我想请问一下这个要怎么跑呀

### ISSUE THREAD

**Issue by Rainysunnyday** [armorunicorn/RECWE#1]
![QQ截图20190909112308](https://user-images.githubusercontent.com/38498080/64501973-5288de00-d2f6-11e9-8630-0a1ca9c550cb.png)

**Comment by armorunicorn** [comment]
我这个都是乱搞的...具体你看https://github.com/HKUST-KnowComp/JWE 这个吧，我就是在这上面改的。

**Comment by Rainysunnyday** [comment]
乱搞都能搞出来，贼厉害。这个有没有python的啊，不太会c呢。TT

**Comment by armorunicorn** [comment]
应该是没有的，其实框架都是cwe那一套代码，在计算向量的时候做了变化，只看那一部分代码即可

**Comment by armorunicorn** [comment]
Joint Embeddings of Chinese Words, Characters, and Fine-grained Subcharacter Components
这篇文章也是我模仿的来源，也可以看看

**Comment by Rainysunnyday** [comment]
好哒 非常感谢~
